const userTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    SIGN_OUT: 'SIGN_OUT',
    PUNCH_SUCCESS: 'PUNCH_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE'
};

export default userTypes;